"use client";

import { createContext, useContext, useState, ReactNode } from "react";
import type { Locale } from "@/lib/i18n";

type Language = Locale;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children, initialLocale = "ka" }: { children: ReactNode; initialLocale?: Language }) => {
  const [language, setLanguage] = useState<Language>(initialLocale);

  const t = (key: string): string => {
    const translations = language === "ka" ? translationsKa : translationsEn;
    const keys = key.split(".");
    let value: unknown = translations;

    for (const k of keys) {
      // Type guard: check if value is an object with the key
      if (value && typeof value === 'object' && k in value) {
        value = (value as Record<string, unknown>)[k];
      } else {
        // Key not found, return the original key as fallback
        return key;
      }
    }

    // Final type guard: ensure return is always a string
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translationsEn = {
  dashboard: {
    nav: {
      overview: "Overview",
      myLessons: "Lessons",
      favorites: "Favorites",
      notifications: "Notifications",
      settings: "Settings",
      schedule: "Schedule",
      logout: "Log out",
    },
    welcome: "Welcome back",
    welcomeInstructor: "Instructor Dashboard",
    subtitle: "Here's your driving progress.",
    subtitleInstructor: "Manage your schedule and students.",
    stats: {
      totalLessons: "Total Lessons",
      completed: "Completed",
      hoursDriven: "Hours Driven",
      totalTime: "Total time",
      upcoming: "Upcoming",
      scheduled: "Scheduled",
      progress: "Progress",
      toLicense: "To license",
      activeStudents: "Active Students",
      teaching: "Currently teaching",
      hoursTaught: "Hours Taught",
      scheduledLessons: "Scheduled lessons",
      earnings: "Earnings",
      thisMonth: "This month",
    },
    nextLesson: {
      title: "Next Lesson",
      noLesson: "No upcoming lessons",
      notAvailable: "Not available",
      bookNow: "Book a lesson now",
      duration: "Duration",
      location: "Location",
      transmission: "Transmission",
      meetingPoint: "Meeting Point",
      instructor: "Instructor",
      student: "Student",
      viewDetails: "View Details",
      viewLesson: "View Lesson",
      hour: "Hour",
      hours: "Hours",
      tomorrow: "Tomorrow",
    },
    quickActions: {
      findInstructor: "Find Instructor",
      findInstructorDesc: "Browse & book",
      bookLesson: "Book Lesson",
      bookLessonDesc: "Schedule now",
      messages: "Messages",
      messagesDesc: "Chat with instructor",
      myLicense: "My License",
      myLicenseDesc: "View documents",
      addStudent: "Add Student",
      addStudentDesc: "Register new student",
      scheduleLessonDesc: "Book a time slot",
      earningsLabel: "Earnings",
      earningsDesc: "View financial report",
      messagesInstructorDesc: "Chat with students",
    },
    activity: {
      title: "Recent Activity",
      lessonCompleted: "Lesson completed with",
      lessonCompletedSimple: "Lesson completed",
      bookingConfirmed: "Booking confirmed",
      lessonCancelled: "Lesson cancelled",
      reviewLeft: "Review left for",
      noActivity: "No recent activity",
    },
    progressRing: {
      title: "Your Progress",
      toLicense: "to license",
    },
  },
  home: {
    hero: {
      badge: "#1 Rated Driving Platform in 2025",
      title: "Master the Road",
      titleHighlight: "With Confidence",
      description: "Ditch the anxiety. Connect with elite, patient instructors who tailor every lesson to your learning style. Your license is just a few clicks away.",
      searchPlaceholder: "Search by city or instructor",
      findInstructors: "Find Instructors",
      joinStudents: "Join 10,000+ students learning today",
      instructorName: "Nino Kalandadze",
      topRated: "Top Rated Instructor",
      automatic: "Automatic",
      weekendAvailability: "Weekend Availability",
    },
    trust: {
      activeStudents: "Active Students",
      passRate: "Pass Rate",
      verifiedInstructors: "Verified Instructors",
      lessonHours: "Lesson Hours",
    },
    roadmap: {
      title: "Everything you need to pass",
      description: "From finding your perfect instructor to acing the test, we've simplified every step of the journey so you can focus on the road ahead.",
      cta: "Start Your Journey",
      step1Title: "Search & Filter",
      step1Desc: "Enter your city and filter by transmission (manual/auto), price, and rating.",
      step2Title: "Compare Profiles",
      step2Desc: "Read verified reviews, check car types, and view instructor pass rates.",
      step3Title: "Book Instantly",
      step3Desc: "Select a time slot that works for you and pay securely through the platform.",
      step4Title: "Track Progress",
      step4Desc: "Get digital feedback after every lesson and track your readiness for the test.",
    },
    showcase: {
      title: "Meet Our Top Instructors",
      subtitle: "Highly rated professionals ready to teach you.",
      viewAll: "View all instructors",
      specialty: "Specializes in Nervous Students",
      manual: "Manual",
      languages: "Georgian & English",
      perHour: "/hr",
      viewProfile: "View Profile",
    },
    instructorCta: {
      badge: "For Instructors",
      title: "Want to become an instructor?",
      titleLine2: "Start teaching today.",
      description: "Join the fastest-growing driving school platform. We handle the marketing and booking, so you can focus on teaching.",
      benefit1: "Grow your student base",
      benefit2: "Set your own schedule",
      benefit3: "Guaranteed payments",
      benefit4: "Professional tools",
      becomeInstructor: "Become an Instructor",
      learnMore: "Learn More",
      monthlyEarnings: "Monthly Earnings",
    },
  },
  hero: {
    title: "Grow Your Business as a",
    titleHighlight: "Driving Instructor",
    description: "Join the fastest growing platform for driving instructors. Manage bookings, get more students, and streamline your business.",
    becomeInstructor: "Become an Instructor",
    calculator: "Calculator"
  },
  stats: {
    activeStudents: "Active Students",
    bookingsMonthly: "Bookings Monthly",
    instructorEarnings: "Instructor Earnings",
    citiesCovered: "Cities Covered"
  },
  howItWorks: {
    badge: "Simple Process",
    title: "Start your journey in",
    titleHighlight: "4 steps",
    description: "We've streamlined the onboarding process so you can focus on what matters most—teaching students how to drive safely.",
    step1Title: "Create Account",
    step1Desc: "Sign up in minutes. Tell us about your experience, vehicle, and teaching preferences.",
    step2Title: "Verify Documents",
    step2Desc: "Upload your driving instructor license and insurance documents for quick verification.",
    step3Title: "Set Your Schedule",
    step3Desc: "Choose when you want to work. Our calendar system handles the bookings automatically.",
    step4Title: "Start Teaching",
    step4Desc: "Receive booking requests from students and start earning money immediately.",
    cta: "Become an Instructor",
    ctaSubtext: "No credit card required • Free to join"
  },
  calculator: {
    title: "Calculate Your Earnings",
    hourlyRate: "Hourly Rate",
    hoursPerWeek: "Hours per Week",
    weeklyIncome: "Weekly Income",
    monthlyIncome: "Monthly Income",
    yearlyPotential: "Yearly Potential",
    disclaimer: "*Estimates based on your inputs. Actual earnings may vary."
  },
  cta: {
    title: "Ready to Start Teaching?",
    description: "Join our community of professional driving instructors and start growing your business today. It takes less than 5 minutes to get started.",
    button: "Create Instructor Account"
  },
  comparison: {
    title: "Compare: Solo vs.",
    titleHighlight: "Instruktori.ge",
    description: "See why thousands of instructors choose our platform to scale their business",
    feature: "Feature",
    soloTeaching: "Solo Teaching",
    platform: "Instruktori.ge",
    timeManagement: "Time Management",
    timeManagementSolo: "Manual scheduling & constant availability",
    timeManagementPlatform: "Set your own hours, automated booking system",
    adminWork: "Administrative Work",
    adminWorkSolo: "Handle payments, contracts, invoices",
    adminWorkPlatform: "Automated payments, documents, analytics",
    studentAcquisition: "Student Acquisition",
    studentAcquisitionSolo: "Rely on word-of-mouth, personal marketing",
    studentAcquisitionPlatform: "1000+ students looking for instructors",
    monthlyIncome: "Monthly Income Potential",
    monthlyIncomeSolo: "Varies, limited by personal network",
    monthlyIncomePlatform: "₾5,000 - ₾15,000 average",
    paymentProcessing: "Payment Processing",
    paymentProcessingSolo: "Chase students for cash/checks",
    paymentProcessingPlatform: "Automatic daily payouts",
    support: "Support & Resources",
    supportSolo: "Figure things out on your own",
    supportPlatform: "24/7 support, training materials, community",
    analytics: "Business Analytics",
    analyticsSolo: "Manual tracking & spreadsheets",
    analyticsPlatform: "Real-time dashboard, insights, growth tracking",
    ctaText: "Ready to scale your business with Instruktori.ge?",
    ctaButton: "Start Your Free Account"
  },
  testimonials: {
    title: "Instructor Stories",
    description: "Hear from professional instructors who have grown their business with us.",
    since: "Instructor since",
    testimonial1: "Since joining, my schedule is fully booked weeks in advance. The platform handles all the scheduling headaches so I can focus on teaching.",
    testimonial2: "The payment system is flawless. I get paid on time every week, and I don't have to chase students for money anymore. Highly recommended!",
    testimonial3: "I love the flexibility. I can set my own hours and take time off whenever I need. It's the perfect way to manage my driving school business."
  },
  signup: {
    pageTitle: "Instructor Application",
    pageSubtitle: "Please fill in your details accurately.",
    sidebarTitle: "Join Georgia's fastest growing instructor network.",
    sidebarSubtitle: "Complete your application in minutes and start receiving students as soon as you're verified.",
    beYourOwnBoss: "Be Your Own Boss",
    beYourOwnBossDesc: "Work when you want, you choose your schedule",
    guaranteedPayments: "Guaranteed Payments",
    guaranteedPaymentsDesc: "Weekly payouts, every time",
    makeImpact: "Make a Real Impact",
    makeImpactDesc: "Be the hero who helps someone gain their driving freedom",
    back: "Back",
    continue: "Continue",
    submitting: "Submitting...",
    submitApplication: "Submit Application",
    step1: "About You",
    step2: "Vehicle Info",
    step3: "Documents",
    step4: "Review",
    // Step 1
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email Address",
    city: "City",
    selectCity: "Select City",
    phone: "Phone Number",
    dateOfBirth: "Date of Birth",
    address: "Address (Teaching Location)",
    firstNamePlaceholder: "John",
    lastNamePlaceholder: "Doe",
    emailPlaceholder: "john@example.com",
    phonePlaceholder: "555 00 00 00",
    addressPlaceholder: "Chavchavadze street, Tbilisi",
    // Step 2
    vehicleBrand: "Vehicle Brand",
    vehicleRegistration: "Vehicle Registration",
    registrationFormat: "Format: XX-123-XX (Standard Georgian Plates)",
    year: "Year",
    transmission: "Transmission",
    automatic: "Automatic",
    manual: "Manual",
    vehiclePhotos: "Vehicle Photos",
    uploadVehiclePhotos: "Upload Vehicle Photos",
    vehiclePhotosSubtext: "Upload clear photos of your vehicle (front, back, interior)",
    selectFiles: "Select Files",
    // Step 3
    documentsSecure: "Your documents are stored securely and only used for verification purposes. We are GDPR compliant.",
    instructorLicense: "Driving Instructor License",
    licenseSubtext: "Upload clear photos of your license (front & back)",
    professionalCertificate: "Professional Certificate",
    certificateSubtext: "Upload your professional driving instructor certificate",
    addMore: "Add More",
    change: "Change",
    selectFile: "Select File",
    // Step 4
    edit: "Edit",
    name: "Name:",
    emailLabel: "Email:",
    phoneLabel: "Phone:",
    addressLabel: "Address:",
    vehicle: "Vehicle:",
    registrationLabel: "Registration:",
    yearLabel: "Year:",
    transmissionLabel: "Transmission:",
    photos: "Photos:",
    photosUploaded: "photo(s) uploaded",
    notUploaded: "Not uploaded",
    license: "License:",
    filesUploaded: "file(s) uploaded",
    uploaded: "Uploaded",
    professionalCertificateLabel: "Professional Certificate:",
    termsText: "I accept the Terms and Conditions and agree to abide by the platform's rules.",
    privacyText: "I agree to the Privacy Policy and consent to the processing of my personal data.",
    termsLink: "Terms and Conditions",
    privacyLink: "Privacy Policy",
    // Success
    successTitle: "Application Submitted!",
    successMessage: "Thank you for applying to join Instruktori. Our team will review your documents and get back to you within 24-48 hours.",
    returnHome: "Return to Home",
    // Validation
    required: "is required",
    firstNameRequired: "First name is required",
    lastNameRequired: "Last name is required",
    emailRequired: "Email is required",
    cityRequired: "City is required",
    phoneRequired: "Phone number is required",
    addressRequired: "Address is required",
    dobRange: "Date of birth must be between 1950 and 2026",
    nameLettersOnly: "must contain only letters",
    invalidEmail: "Please enter a valid email address",
    phoneDigitsOnly: "Phone number must contain only numbers",
    phone9Digits: "Phone number must be exactly 9 digits",
    phoneStart5: "Phone number must start with 5",
    vehicleBrandRequired: "Vehicle brand is required",
    registrationRequired: "Registration is required",
    yearRequired: "Year is required",
    transmissionRequired: "Transmission is required",
    registrationFormat2: "Format must be XX-123-XX (e.g., AA-123-AA)",
    vehiclePhotoRequired: "At least one vehicle photo is required",
    licenseRequired: "Instructor license is required",
    termsRequired: "You must accept the Terms & Conditions",
    privacyRequired: "You must accept the Privacy Policy",
    // File limits
    maxVehiclePhotos: "Maximum 5 vehicle photos allowed",
    maxLicenseFiles: "Maximum 2 license files allowed",
    maxCertificateFiles: "Maximum 1 certificate file allowed",
    fileTooLarge: "File size must be under 5 MB",
    // API status
    verifyingBackend: "Verifying backend...",
    backendConnected: "Backend connected",
    backendUnreachable: "Backend unreachable",
    checkingConnection: "Checking backend connection...",
    apiReachable: "API is reachable",
    unableToReach: "Unable to reach backend. Check NEXT_PUBLIC_API_URL.",
  },
  reviews: {
    title: "Student Reviews",
    subtitle: "What learners say about this instructor",
    rateExperience: "Rate your experience",
    placeholder: "Share your experience...",
    postReview: "Post Review",
    signInPrompt: "Sign in to leave a review and join the conversation",
    noReviews: "No reviews yet",
    beFirst: "Be the first to share your experience!",
    latestReviews: "Latest Reviews",
    newest: "Newest First",
    oldest: "Oldest First",
    mostHelpful: "Most Helpful",
    loadMore: "Load More Reviews",
    loading: "Loading...",
    reply: "Reply",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    replyPlaceholder: "Reply...",
    rating: "Rating:",
    hide: "Hide",
    show: "Show",
    replySingular: "reply",
    replyPlural: "replies",
    confirmDelete: "Are you sure you want to delete this comment?",
    selectRatingAndReview: "Please select a rating and write a review",
    selectRating: "Please select a rating",
    writeReview: "Please write a review",
    signIn: "Sign In",
  },
  faq: {
    title: "Frequently Asked Questions",
    description: "Everything you need to know about becoming an instructor.",
    q1: "How much does it cost to join?",
    a1: "Creating a profile is completely free. We only charge a small commission fee on completed bookings. There are no monthly subscription fees or hidden costs.",
    q2: "When do I get paid?",
    a2: "Payments are processed daily. Earnings from completed lessons are transferred directly to your bank account every day.",
    q3: "Can I set my own prices?",
    a3: "Yes, absolutely! You have full control over your hourly rates and package prices. You can adjust them at any time through your dashboard.",
    q4: "What documents do I need?",
    a4: "You'll need a valid driving instructor license, proof of vehicle insurance, and a clean background check. We'll guide you through the verification process.",
    q5: "How does the calendar work?",
    a5: "You set your availability in our calendar system. Students can only book slots that you've marked as available. You can sync it with your personal calendar too.",
    q6: "What is cancellation protection?",
    a6: "Our cancellation protection policy ensures you're compensated if a student cancels a lesson within 24 hours of the scheduled time. You'll receive 50% of the lesson fee for late cancellations."
  },
  booking: {
    loadingDetails: "Loading booking details...",
    somethingWentWrong: "Something went wrong",
    backToProfile: "Back to Profile",
    bookALesson: "Book a Lesson",
    with: "with",
    perLesson: "/lesson",
    stepTime: "Time",
    stepConfirm: "Confirm",
    stepPayment: "Payment",
    stepDone: "Done",
    noAvailableSlots: "No Available Slots",
    noSlotsDescription: "This instructor hasn't set up any available time slots yet.",
    checkBackLater: "Please check back later or try another instructor.",
    availableTimes: "Available Times",
    selectDatePrompt: "Select a date from the calendar to see available time slots",
    availableSlotsFor: "Available slots for",
    slotsSelected: "slots selected",
    min: "min",
    continueToConfirm: "Continue to Confirm",
    confirmBooking: "Confirm Booking",
    bookingFailed: "Booking failed",
    drivingLesson: "Driving Lesson",
    drivingLessons: "Driving Lessons",
    total: "total",
    notesLabel: "Notes for Instructor (Optional)",
    notesPlaceholder: "Any special requests or things the instructor should know?",
    cancellationPolicy: "Free cancellation up to 24 hours before the lesson start time. Late cancellations may be charged 50% of the lesson fee.",
    back: "Back",
    confirm: "Proceed to Payment",
    bookingInProgress: "Booking...",
    bookingConfirmedTitle: "Booking Confirmed!",
    bookingConfirmedDesc: "have been scheduled.",
    confirmationEmail: "You'll receive a confirmation email shortly.",
    redirecting: "Redirecting to dashboard...",
    legendAvailable: "Available",
    legendViewing: "Viewing",
    legendSelected: "Selected",
    weekMon: "Mon",
    weekTue: "Tue",
    weekWed: "Wed",
    weekThu: "Thu",
    weekFri: "Fri",
    weekSat: "Sat",
    weekSun: "Sun",
    reserving: "Reserving...",
    slotsReservedFor: "Slots reserved for you",
    completeBeforeExpiry: "Complete your booking before time runs out",
    reservationExpiredTitle: "Reservation Expired",
    reservationExpiredDesc: "Your temporary hold has expired and the slots are now available to others. Please select new time slots.",
    selectNewSlots: "Select New Slots",
    slotsAlreadyTaken: "The selected slots are no longer available. Please choose different time slots.",
    someSlotsFailed: "Some slots could not be confirmed. They may have expired.",
    addAnotherDay: "Add Another Day",
    wantAnotherDay: "Want to add another day?",
    doneSelectingDays: "No, continue",
    paymentTitle: "Payment",
    paymentSubtitle: "Complete your payment to confirm the booking",
    orderSummary: "Order Summary",
    paymentMethod: "Payment Method",
    cardNumber: "Card Number",
    cardHolder: "Cardholder Name",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    cardNumberPlaceholder: "1234 5678 9012 3456",
    cardHolderPlaceholder: "Name on card",
    expiryPlaceholder: "MM/YY",
    cvvPlaceholder: "123",
    billingAddress: "Billing Address",
    billingAddressPlaceholder: "Enter your billing address",
    payNow: "Pay ₾",
    paying: "Processing...",
    securePayment: "Secured by BOG Payment Gateway",
    bogRedirectNote: "You will be redirected to BOG secure payment page to complete your transaction.",
  },
  settings: {
    title: "Settings",
    subtitle: "Manage your account and preferences.",
    tabs: {
      profile: "Profile",
      instructorProfile: "Instructor Profile",
      account: "Account",
      notifications: "Notifications",
    },
    profile: {
      photoTitle: "Profile Photo",
      photoDesc: "Manage your photo in Account settings.",
      updateInAccount: "Update in Account",
      availability: "Availability",
      availabilityDesc: "Set your availability using the responsive calendar.",
      openCalendar: "Open Calendar",
      personalInfo: "Personal Information",
      notInstructor: "You are not an instructor yet",
      title: "Title",
      locatedAt: "Located At",
      googleMapsUrl: "Google Maps URL",
      languageSkills: "Language Skills",
      other: "Other",
      selected: "Selected",
      none: "None",
      automaticCityPrice: "Automatic City Price",
      automaticYardPrice: "Automatic Yard Price",
      manualCityPrice: "Manual City Price",
      manualYardPrice: "Manual Yard Price",
      firstName: "Applicant First Name",
      lastName: "Applicant Last Name",
      contactEmail: "Contact Email",
      phone: "Phone",
      city: "Applicant City",
      dateOfBirth: "Date of Birth",
      description: "Description",
      address: "Applicant Address",
      emailSecurityNote: "To update email, password, or security settings, go to the Account tab.",
      profileUpdated: "Profile updated successfully",
      discardChanges: "Discard Changes",
      saveChanges: "Save Changes",
      vehiclePhotos: "Vehicle Photos",
      uploadPhotos: "Upload Photos",
      limitReached: "Limit Reached",
      loadingPhotos: "Loading photos...",
      noPhotos: "No vehicle photos uploaded yet.",
      photosUpdated: "Vehicle photos updated successfully",
      photoRemoved: "Vehicle photo removed successfully",
    },
    account: {
      title: "Account Management",
      desc: "Manage your account settings, security, and connected accounts through Clerk.",
    },
    notifications: {
      title: "Notifications",
      lessonReminders: "Lesson Reminders",
      lessonRemindersDesc: "Get notified 24h before your lesson starts",
      newMessages: "New Messages",
      newMessagesDesc: "Receive emails when you get a new message",
      marketingUpdates: "Marketing Updates",
      marketingUpdatesDesc: "Receive news about features and promotions",
      newBookings: "New Bookings",
      newBookingsDesc: "Get notified when a student books a lesson",
      cancellations: "Cancellations",
      cancellationsDesc: "Get notified when a lesson is cancelled",
    },
  },
};

const translationsKa = {
  dashboard: {
    nav: {
      overview: "მიმოხილვა",
      myLessons: "ჩემი გაკვეთილები",
      favorites: "რჩეულები",
      notifications: "შეტყობინებები",
      settings: "პარამეტრები",
      schedule: "განრიგი",
      logout: "გასვლა",
    },
    welcome: "გამარჯობა",
    welcomeInstructor: "ინსტრუქტორის პანელი",
    subtitle: "აი შენი მართვის პროგრესი.",
    subtitleInstructor: "მართე შენი განრიგი და მოსწავლეები.",
    stats: {
      totalLessons: "სულ გაკვეთილები",
      completed: "დასრულებული",
      hoursDriven: "მართვის საათები",
      totalTime: "სულ დრო",
      upcoming: "მომავალი",
      scheduled: "დაგეგმილი",
      progress: "პროგრესი",
      toLicense: "მოწმობამდე",
      activeStudents: "აქტიური მოსწავლეები",
      teaching: "ამჟამად ასწავლი",
      hoursTaught: "სწავლების საათები",
      scheduledLessons: "დაგეგმილი გაკვეთილები",
      earnings: "შემოსავალი",
      thisMonth: "ამ თვეში",
    },
    nextLesson: {
      title: "მომდევნო გაკვეთილი",
      noLesson: "მომავალი გაკვეთილები არ არის",
      notAvailable: "არ არის ხელმისაწვდომი",
      bookNow: "დაჯავშნე გაკვეთილი",
      duration: "ხანგრძლივობა",
      location: "ლოკაცია",
      transmission: "ტრანსმისია",
      meetingPoint: "შეხვედრის ადგილი",
      instructor: "ინსტრუქტორი",
      student: "მოსწავლე",
      viewDetails: "დეტალების ნახვა",
      viewLesson: "გაკვეთილის ნახვა",
      hour: "საათი",
      hours: "საათი",
      tomorrow: "ხვალ",
    },
    quickActions: {
      findInstructor: "ინსტრუქტორის ძიება",
      findInstructorDesc: "დათვალიერე და დაჯავშნე",
      bookLesson: "გაკვეთილის ჯავშანი",
      bookLessonDesc: "დაგეგმე ახლავე",
      messages: "შეტყობინებები",
      messagesDesc: "ინსტრუქტორთან ჩატი",
      myLicense: "ჩემი მოწმობა",
      myLicenseDesc: "დოკუმენტების ნახვა",
      addStudent: "მოსწავლის დამატება",
      addStudentDesc: "ახალი მოსწავლის რეგისტრაცია",
      scheduleLessonDesc: "დროის სლოტის დაჯავშნა",
      earningsLabel: "შემოსავალი",
      earningsDesc: "ფინანსური ანგარიშის ნახვა",
      messagesInstructorDesc: "მოსწავლეებთან ჩატი",
    },
    activity: {
      title: "ბოლო აქტივობა",
      lessonCompleted: "გაკვეთილი დასრულდა",
      lessonCompletedSimple: "გაკვეთილი დასრულდა",
      bookingConfirmed: "ჯავშანი დადასტურდა",
      lessonCancelled: "გაკვეთილი გაუქმდა",
      reviewLeft: "შეფასება დატოვეთ",
      noActivity: "ბოლო აქტივობა არ არის",
    },
    progressRing: {
      title: "შენი პროგრესი",
      toLicense: "მოწმობამდე",
    },
  },
  home: {
    hero: {
      badge: "#1 პლატფორმა გამოცდის ჩასაბარებლად",
      title: "ჩააბარე გამოცდა",
      titleHighlight: "თავდაჯერებულმა",
      description: "ნერვიულობა წარსულს ჩააბარე. აირჩიე ინსტრუქტორი, რომელიც შენზე მორგებულად გასწავლის, დაჯავშნე გაკვეთილი, ისწავლე ისე, როგორც შენთვის ყველაზე კომფორტულია და იგრძენი სიმშვიდე გზაზე.",
      searchPlaceholder: "ძიება ქალაქით ან სახელით",
      findInstructors: "ინსტრუქტორის ძიება",
      joinStudents: "შემოუერთდი 1000+ მოსწავლეს",
      instructorName: "ნინო კალანდაძე",
      topRated: "მაღალ რეიტინგული ინსტრუქტორი",
      automatic: "ავტომატიკა",
      weekendAvailability: "შაბათ-კვირას ხელმისაწვდომი",
    },
    trust: {
      activeStudents: "აქტიური მოსწავლე",
      passRate: "აბარებს გამოცდას",
      verifiedInstructors: "ინსტრუქტორი",
      lessonHours: "გაკვეთილების საათი",
    },
    roadmap: {
      title: "ყველაფერი, რაც ჩაბარებისთვის გჭირდება",
      description: "იდეალური ინსტრუქტორის მოძებნიდან გამოცდის წარმატებით ჩაბარებამდე. ჩვენ ყველა ნაბიჯი გავამარტივეთ, რათა შენ მაქსიმალურად მზად იყო ჩასაბარებლად.",
      cta: "დაიწყე სწავლა",
      step1Title: "ძიება და ფილტრაცია",
      step1Desc: "შეიყვანე შენთვის სასურველი ქალაქი და გაფილტრე გადაცემათა კოლოფის ტიპით (მექანიკა/ავტომატიკა), ფასით და რეიტინგით.",
      step2Title: "დაჯავშნე მარტივად",
      step2Desc: "აირჩიე შენთვის მოსახერხებელი დრო და გადაიხადე უსაფრთხოდ პლატფორმის საშუალებით, თითის რამოდენიმე დაწკაპებით.",
      step3Title: "ქალაქის ჯავშანი",
      step3Desc: "გამოიყენე ჩვენი შეტყობინების სერვისი და გაიგე პირველმა როდის იხსნება ქალაქის ჯავშნები, რათა თვე არ დაკარგო.",
      step4Title: "იყავი მზად",
      step4Desc: "გაიარე სიმულაციები, უყურე მარშრუტებს და დაიზეპირე წინა-საგამოცდო ჩეკლისტი.",
    },
    showcase: {
      title: "ხალხის რჩეული ინსტრუქტორები",
      subtitle: "მაღალი შეფასების პროფესიონალები, მზად, დაგეხმარონ ჩაბარებაში.",
      viewAll: "ყველა ინსტრუქტორის ნახვა",
      specialty: "ნერვიული მოსწავლეების სპეციალისტი",
      manual: "მექანიკა",
      languages: "ქართული და ინგლისური",
      perHour: "/სთ",
      viewProfile: "პროფილის ნახვა",
    },
    instructorCta: {
      badge: "ინსტრუქტორებისთვის",
      title: "გსურს გახდე პარტნიორი?",
      titleLine2: "დაიწყე სწავლება დღესვე.",
      description: "შემოუერთდი ყველაზე სწრაფად მზარდ ავტოსკოლის პლატფორმას. ჩვენ მოგვყავს კლიენტები, შენ კი სწავლებაზე ფოკუსირდები.",
      benefit1: "გაზარდე მოსავლეთა რიცხვი",
      benefit2: "დააწესე საკუთარი განრიგი",
      benefit3: "სტაბილური შემოსავალი",
      benefit4: "მარტივი ჯავშნების მართვა",
      becomeInstructor: "გახდი პარტნიორი",
      learnMore: "გაიგე მეტი",
      monthlyEarnings: "საშუალო ყოველთვიური შემოსავალი",
    },
  },
  hero: {
    title: "გაზარდეთ თქვენი ბიზნესი როგორც",
    titleHighlight: "მართვის ინსტრუქტორი",
    description: "შემოუერთდით სწრაფად მზარდ პლატფორმას მართვის ინსტრუქტორებისთვის. მართეთ ბრონირებები, მიიღეთ მეტი სტუდენტი და გაამარტივეთ თქვენი ბიზნესი.",
    becomeInstructor: "გახდი ინსტრუქტორი",
    calculator: "კალკულატორი"
  },
  stats: {
    activeStudents: "აქტიური სტუდენტები",
    bookingsMonthly: "ყოველთვიური ბრონირებები",
    instructorEarnings: "ინსტრუქტორის შემოსავალი",
    citiesCovered: "ქალაქები დაფარული"
  },
  howItWorks: {
    badge: "მარტივი პროცესი",
    title: "დაიწყეთ თქვენი მოგზაურობა",
    titleHighlight: "4 ნაბიჯში",
    description: "ჩვენ გავამარტივეთ რეგისტრაციის პროცესი, რათა შეძლოთ კონცენტრირება მთავარზე - სტუდენტებისთვის უსაფრთხო მართვის სწავლებაზე.",
    step1Title: "შექმენით ანგარიში",
    step1Desc: "დარეგისტრირდით წუთებში. მოგვიყევით თქვენი გამოცდილების, მანქანის და სწავლების პრეფერენციების შესახებ.",
    step2Title: "დაადასტურეთ დოკუმენტები",
    step2Desc: "ატვირთეთ თქვენი მართვის ინსტრუქტორის ლიცენზია და დაზღვევის დოკუმენტები სწრაფი გადამოწმებისთვის.",
    step3Title: "დააყენეთ თქვენი განრიგი",
    step3Desc: "აირჩიეთ როდის გსურთ მუშაობა. ჩვენი კალენდარის სისტემა ავტომატურად მართავს ბრონირებებს.",
    step4Title: "დაიწყეთ სწავლება",
    step4Desc: "მიიღეთ ბრონირების მოთხოვნები სტუდენტებისგან და დაწყეთ ფულის გამომუშავება დაუყოვნებლივ.",
    cta: "გახდი ინსტრუქტორი",
    ctaSubtext: "საკრედიტო ბარათი არ არის საჭირო • უფასოდ გაწევრიანება"
  },
  calculator: {
    title: "გამოთვალეთ თქვენი შემოსავალი",
    hourlyRate: "საათობრივი განაკვეთი",
    hoursPerWeek: "საათები კვირაში",
    weeklyIncome: "კვირეული შემოსავალი",
    monthlyIncome: "ყოველთვიური შემოსავალი",
    yearlyPotential: "წლიური პოტენციალი",
    disclaimer: "*შეფასებები დაფუძნებულია თქვენს მონაცემებზე. რეალური შემოსავალი შეიძლება განსხვავდებოდეს."
  },
  cta: {
    title: "მზად ხართ სწავლების დასაწყებად?",
    description: "შემოუერთდით პროფესიონალი მართვის ინსტრუქტორების ჩვენს საზოგადოებას და დაიწყეთ თქვენი ბიზნესის გაზრდა დღესვე. ეს 5 წუთზე ნაკლებ დროს სჭირდება.",
    button: "შექმენით ინსტრუქტორის ანგარიში"
  },
  comparison: {
    title: "შეადარეთ: სოლო vs.",
    titleHighlight: "Instruktori.ge",
    description: "ნახეთ რატომ ირჩევენ ათასობით ინსტრუქტორები ჩვენს პლატფორმას თავიანთი ბიზნესის გასაზრდელად",
    feature: "ფუნქცია",
    soloTeaching: "სოლო სწავლება",
    platform: "Instruktori.ge",
    timeManagement: "დროის მართვა",
    timeManagementSolo: "ხელით დაგეგმვა და მუდმივი ხელმისაწვდომობა",
    timeManagementPlatform: "დააყენეთ თქვენი საათები, ავტომატური ბრონირების სისტემა",
    adminWork: "ადმინისტრაციული სამუშაო",
    adminWorkSolo: "გადახდების, კონტრაქტების, ინვოისების მართვა",
    adminWorkPlatform: "ავტომატური გადახდები, დოკუმენტები, ანალიტიკა",
    studentAcquisition: "სტუდენტების მოპოვება",
    studentAcquisitionSolo: "დამოკიდებულება სიტყვიერ რეკლამაზე, პირადი მარკეტინგი",
    studentAcquisitionPlatform: "1000+ სტუდენტი ეძებს ინსტრუქტორებს",
    monthlyIncome: "ყოველთვიური შემოსავლის პოტენციალი",
    monthlyIncomeSolo: "განსხვავებული, შეზღუდული პირადი ქსელით",
    monthlyIncomePlatform: "₾5,000 - ₾15,000 საშუალოდ",
    paymentProcessing: "გადახდის დამუშავება",
    paymentProcessingSolo: "სტუდენტების უკან დევნა ფულის/ჩეკებისთვის",
    paymentProcessingPlatform: "ავტომატური ყოველდღიური გადახდები",
    support: "მხარდაჭერა და რესურსები",
    supportSolo: "თავად გაარკვიეთ ყველაფერი",
    supportPlatform: "24/7 მხარდაჭერა, სასწავლო მასალები, საზოგადოება",
    analytics: "ბიზნეს ანალიტიკა",
    analyticsSolo: "ხელით თვალყურის დევნება და ცხრილები",
    analyticsPlatform: "რეალურ დროში მონაცემთა პანელი, ინსაითები, ზრდის თვალყურის დევნება",
    ctaText: "მზად ხართ გაზარდოთ თქვენი ბიზნესი Instruktori.ge-თან ერთად?",
    ctaButton: "დაიწყეთ თქვენი უფასო ანგარიში"
  },
  testimonials: {
    title: "ინსტრუქტორების ისტორიები",
    description: "მოისმინეთ პროფესიონალი ინსტრუქტორებისგან, რომლებმაც გაზარდეს თავიანთი ბიზნესი ჩვენთან ერთად.",
    since: "ინსტრუქტორი",
    testimonial1: "შემოერთების შემდეგ, ჩემი განრიგი სრულად დაჯავშნილია კვირებით წინ. პლატფორმა მართავს ყველა დაგეგმვის თავისტკივილს, რათა შევძლო კონცენტრირება სწავლებაზე.",
    testimonial2: "გადახდის სისტემა უკიდურესად მშვენიერია. ფულს დროულად ვიღებ ყოველ კვირას და აღარ მიწევს სტუდენტების უკან დევნა. ძალიან გირჩევთ!",
    testimonial3: "მიყვარს მოქნილობა. შემიძლია დავაყენო ჩემი საათები და დამიკავდეს დრო როცა კი მჭირდება. ეს სრულყოფილი გზაა ჩემი ავტოსკოლის ბიზნესის მართვისთვის."
  },
  signup: {
    pageTitle: "ინსტრუქტორის განაცხადი",
    pageSubtitle: "გთხოვთ ზუსტად შეავსოთ თქვენი მონაცემები.",
    sidebarTitle: "შემოუერთდი საქართველოს ყველაზე სწრაფად მზარდ ინსტრუქტორთა ქსელს.",
    sidebarSubtitle: "შეავსე განაცხადი წუთებში და დაიწყე მოსწავლეების მიღება ვერიფიკაციის შემდეგ.",
    beYourOwnBoss: "იყავი საკუთარი თავის უფროსი",
    beYourOwnBossDesc: "იმუშავე სურვილისამებრ, შენ ირჩევ განრიგს",
    guaranteedPayments: "გარანტირებული გადახდები",
    guaranteedPaymentsDesc: "ყოველკვირეული ანგარიშსწორება, ყოველთვის",
    makeImpact: "მოახდინე რეალური გავლენა",
    makeImpactDesc: "გახდი გმირი, ვინც ვინმეს მართვის თავისუფლებას აძლევს",
    back: "უკან",
    continue: "გაგრძელება",
    submitting: "იგზავნება...",
    submitApplication: "განაცხადის გაგზავნა",
    step1: "შენ შესახებ",
    step2: "ავტომობილი",
    step3: "დოკუმენტები",
    step4: "მიმოხილვა",
    // Step 1
    firstName: "სახელი",
    lastName: "გვარი",
    email: "ელ. ფოსტა",
    city: "ქალაქი",
    selectCity: "აირჩიეთ ქალაქი",
    phone: "ტელეფონის ნომერი",
    dateOfBirth: "დაბადების თარიღი",
    address: "მისამართი (სწავლების ადგილი)",
    firstNamePlaceholder: "გიორგი",
    lastNamePlaceholder: "კალანდაძე",
    emailPlaceholder: "giorgi@example.com",
    phonePlaceholder: "555 00 00 00",
    addressPlaceholder: "ჭავჭავაძის ქუჩა, თბილისი",
    // Step 2
    vehicleBrand: "ავტომობილის მარკა",
    vehicleRegistration: "სარეგისტრაციო ნომერი",
    registrationFormat: "ფორმატი: XX-123-XX (სტანდარტული ქართული ნომრები)",
    year: "წელი",
    transmission: "ტრანსმისია",
    automatic: "ავტომატიკა",
    manual: "მექანიკა",
    vehiclePhotos: "ავტომობილის ფოტოები",
    uploadVehiclePhotos: "ატვირთეთ ავტომობილის ფოტოები",
    vehiclePhotosSubtext: "ატვირთეთ ავტომობილის ნათელი ფოტოები (წინა, უკანა, სალონი)",
    selectFiles: "ფაილების არჩევა",
    // Step 3
    documentsSecure: "თქვენი დოკუმენტები უსაფრთხოდ ინახება და გამოიყენება მხოლოდ ვერიფიკაციის მიზნით. ჩვენ ვიცავთ GDPR-ს.",
    instructorLicense: "მართვის ინსტრუქტორის ლიცენზია",
    licenseSubtext: "ატვირთეთ ლიცენზიის ნათელი ფოტოები (წინა და უკანა მხარე)",
    professionalCertificate: "პროფესიული სერტიფიკატი",
    certificateSubtext: "ატვირთეთ პროფესიული ინსტრუქტორის სერტიფიკატი",
    addMore: "დამატება",
    change: "შეცვლა",
    selectFile: "ფაილის არჩევა",
    // Step 4
    edit: "რედაქტირება",
    name: "სახელი:",
    emailLabel: "ელ. ფოსტა:",
    phoneLabel: "ტელეფონი:",
    addressLabel: "მისამართი:",
    vehicle: "ავტომობილი:",
    registrationLabel: "რეგისტრაცია:",
    yearLabel: "წელი:",
    transmissionLabel: "ტრანსმისია:",
    photos: "ფოტოები:",
    photosUploaded: "ფოტო ატვირთულია",
    notUploaded: "არ არის ატვირთული",
    license: "ლიცენზია:",
    filesUploaded: "ფაილი ატვირთულია",
    uploaded: "ატვირთულია",
    professionalCertificateLabel: "პროფესიული სერტიფიკატი:",
    termsText: "ვეთანხმები წესებსა და პირობებს და ვიღებ პლატფორმის რეგულაციებს.",
    privacyText: "ვეთანხმები კონფიდენციალურობის პოლიტიკას და თანხმობას ვაძლევ ჩემი პერსონალური მონაცემების დამუშავებაზე.",
    termsLink: "წესები და პირობები",
    privacyLink: "კონფიდენციალურობის პოლიტიკა",
    // Success
    successTitle: "განაცხადი გაგზავნილია!",
    successMessage: "გმადლობთ Instruktori-ში განაცხადის გამოგზავნისთვის. ჩვენი გუნდი განიხილავს თქვენს დოკუმენტებს და გიპასუხებთ 24-48 საათში.",
    returnHome: "მთავარ გვერდზე დაბრუნება",
    // Validation
    required: "აუცილებელია",
    firstNameRequired: "სახელი აუცილებელია",
    lastNameRequired: "გვარი აუცილებელია",
    emailRequired: "ელ. ფოსტა აუცილებელია",
    cityRequired: "ქალაქი აუცილებელია",
    phoneRequired: "ტელეფონის ნომერი აუცილებელია",
    addressRequired: "მისამართი აუცილებელია",
    dobRange: "დაბადების თარიღი უნდა იყოს 1950-დან 2026-მდე",
    nameLettersOnly: "უნდა შეიცავდეს მხოლოდ ასოებს",
    invalidEmail: "გთხოვთ შეიყვანოთ ვალიდური ელ. ფოსტის მისამართი",
    phoneDigitsOnly: "ტელეფონის ნომერი უნდა შეიცავდეს მხოლოდ ციფრებს",
    phone9Digits: "ტელეფონის ნომერი უნდა იყოს ზუსტად 9 ციფრი",
    phoneStart5: "ტელეფონის ნომერი უნდა იწყებოდეს 5-ით",
    vehicleBrandRequired: "ავტომობილის მარკა აუცილებელია",
    registrationRequired: "სარეგისტრაციო ნომერი აუცილებელია",
    yearRequired: "წელი აუცილებელია",
    transmissionRequired: "ტრანსმისია აუცილებელია",
    registrationFormat2: "ფორმატი უნდა იყოს XX-123-XX (მაგ., AA-123-AA)",
    vehiclePhotoRequired: "მინიმუმ ერთი ავტომობილის ფოტო აუცილებელია",
    licenseRequired: "ინსტრუქტორის ლიცენზია აუცილებელია",
    termsRequired: "წესებისა და პირობების მიღება აუცილებელია",
    privacyRequired: "კონფიდენციალურობის პოლიტიკის მიღება აუცილებელია",
    // File limits
    maxVehiclePhotos: "მაქსიმუმ 5 ავტომობილის ფოტოა დაშვებული",
    maxLicenseFiles: "მაქსიმუმ 2 ლიცენზიის ფაილია დაშვებული",
    maxCertificateFiles: "მაქსიმუმ 1 სერტიფიკატის ფაილია დაშვებული",
    fileTooLarge: "ფაილის ზომა 5 მბ-ზე ნაკლები უნდა იყოს",
    // API status
    verifyingBackend: "სერვერის შემოწმება...",
    backendConnected: "სერვერთან დაკავშირებულია",
    backendUnreachable: "სერვერი მიუწვდომელია",
    checkingConnection: "სერვერთან კავშირის შემოწმება...",
    apiReachable: "API ხელმისაწვდომია",
    unableToReach: "სერვერთან დაკავშირება ვერ მოხერხდა.",
  },
  reviews: {
    title: "მოსწავლეთა შეფასებები",
    subtitle: "რას ამბობენ მოსწავლეები ამ ინსტრუქტორზე",
    rateExperience: "შეაფასეთ თქვენი გამოცდილება",
    placeholder: "გაგვიზიარეთ თქვენი გამოცდილება...",
    postReview: "შეფასების გამოქვეყნება",
    signInPrompt: "შეფასების დასატოვებლად გაიარეთ ავტორიზაცია",
    noReviews: "შეფასებები ჯერ არ არის",
    beFirst: "იყავით პირველი, ვინც გამოცდილებას გააზიარებს!",
    latestReviews: "ბოლო შეფასებები",
    newest: "უახლესი",
    oldest: "ძველი",
    mostHelpful: "ყველაზე სასარგებლო",
    loadMore: "მეტი შეფასების ჩატვირთვა",
    loading: "იტვირთება...",
    reply: "პასუხი",
    edit: "რედაქტირება",
    delete: "წაშლა",
    save: "შენახვა",
    cancel: "გაუქმება",
    replyPlaceholder: "პასუხი...",
    rating: "შეფასება:",
    hide: "დამალვა",
    show: "ჩვენება",
    replySingular: "პასუხი",
    replyPlural: "პასუხი",
    confirmDelete: "დარწმუნებული ხართ, რომ გსურთ ამ კომენტარის წაშლა?",
    selectRatingAndReview: "გთხოვთ აირჩიოთ შეფასება და დაწეროთ მიმოხილვა",
    selectRating: "გთხოვთ აირჩიოთ შეფასება",
    writeReview: "გთხოვთ დაწეროთ მიმოხილვა",
    signIn: "ავტორიზაცია",
  },
  faq: {
    title: "ხშირად დასმული შეკითხვები",
    description: "ყველაფერი რაც თქვენ უნდა იცოდეთ ინსტრუქტორად გახდომის შესახებ.",
    q1: "რამდენი ღირს გაწევრიანება?",
    a1: "პროფილის შექმნა მთლიანად უფასოა. ჩვენ ვიღებთ მხოლოდ მცირე საკომისიოს დასრულებულ ბრონირებებზე. არ არის ყოველთვიური გამოწერის საფასური ან დამალული ხარჯები.",
    q2: "როდის ვიღებ ფულს?",
    a2: "გადახდები მუშავდება ყოველდღიურად. დასრულებული გაკვეთილებიდან მიღებული შემოსავალი გადაირიცხება თქვენს საბანკო ანგარიშზე ყოველდღე.",
    q3: "შემიძლია დავაყენო ჩემი საკუთარი ფასები?",
    a3: "დიახ, აბსოლუტურად! თქვენ გაქვთ სრული კონტროლი თქვენს საათობრივ განაკვეთებსა და პაკეტის ფასებზე. შეგიძლიათ შეცვალოთ ისინი ნებისმიერ დროს თქვენი დაფის მეშვეობით.",
    q4: "რა დოკუმენტები მჭირდება?",
    a4: "დაგჭირდებათ მოქმედი მართვის ინსტრუქტორის ლიცენზია, მანქანის დაზღვევის დამადასტურებელი დოკუმენტი და სუფთა ბიოგრაფია. ჩვენ გაგიმარტივებთ გადამოწმების პროცესს.",
    q5: "როგორ მუშაობს კალენდარი?",
    a5: "თქვენ აყენებთ თქვენს ხელმისაწვდომობას ჩვენს კალენდარის სისტემაში. სტუდენტებს შეუძლიათ დაჯავშნონ მხოლოდ ის სლოტები, რომლებიც თქვენ მონიშნული გაქვთ ხელმისაწვდომად. შეგიძლიათ სინქრონიზება გაუკეთოთ თქვენს პირად კალენდარსაც.",
    q6: "რა არის გაუქმების დაცვა?",
    a6: "ჩვენი გაუქმების დაცვის პოლიტიკა უზრუნველყოფს, რომ კომპენსაციას მიიღებთ, თუ სტუდენტი გააუქმებს გაკვეთილს დაგეგმილი დროიდან 24 საათის განმავლობაში. მიიღებთ გაკვეთილის საფასურის 50%-ს გვიან გაუქმებისთვის."
  },
  booking: {
    loadingDetails: "იტვირთება ჯავშნის დეტალები...",
    somethingWentWrong: "დაფიქსირდა შეცდომა",
    backToProfile: "პროფილზე დაბრუნება",
    bookALesson: "გაკვეთილის დაჯავშნა",
    with: "",
    perLesson: "/გაკვეთილი",
    stepTime: "დრო",
    stepConfirm: "დადასტურება",
    stepPayment: "გადახდა",
    stepDone: "მზადაა",
    noAvailableSlots: "ხელმისაწვდომი სლოტები არ არის",
    noSlotsDescription: "ამ ინსტრუქტორს ჯერ არ აქვს დაყენებული ხელმისაწვდომი სლოტები.",
    checkBackLater: "გთხოვთ, სცადოთ მოგვიანებით ან აირჩიოთ სხვა ინსტრუქტორი.",
    availableTimes: "ხელმისაწვდომი დრო",
    selectDatePrompt: "აირჩიეთ თარიღი კალენდრიდან ხელმისაწვდომი სლოტების სანახავად",
    availableSlotsFor: "ხელმისაწვდომი სლოტები",
    slotsSelected: "სლოტი არჩეულია",
    min: "წთ",
    continueToConfirm: "გაგრძელება",
    confirmBooking: "ჯავშნის დადასტურება",
    bookingFailed: "ჯავშანი ვერ შეიქმნა",
    drivingLesson: "მართვის გაკვეთილი",
    drivingLessons: "მართვის გაკვეთილები",
    total: "ჯამი",
    notesLabel: "შენიშვნები ინსტრუქტორისთვის (არასავალდებულო)",
    notesPlaceholder: "რაიმე სპეციალური მოთხოვნა ან ინფორმაცია ინსტრუქტორისთვის?",
    cancellationPolicy: "უფასო გაუქმება გაკვეთილის დაწყებამდე 24 საათით ადრე. გვიანი გაუქმებისთვის შეიძლება დაგეკისროთ გაკვეთილის საფასურის 50%.",
    back: "უკან",
    confirm: "გადახდაზე გადასვლა",
    bookingInProgress: "იჯავშნება...",
    bookingConfirmedTitle: "ჯავშანი დადასტურდა!",
    bookingConfirmedDesc: "დაიგეგმა.",
    confirmationEmail: "მალე მიიღებთ დადასტურების ელ-წერილს.",
    redirecting: "გადამისამართება დაფაზე...",
    legendAvailable: "ხელმისაწვდომი",
    legendViewing: "ნახვა",
    legendSelected: "არჩეული",
    weekMon: "ორშ",
    weekTue: "სამ",
    weekWed: "ოთხ",
    weekThu: "ხუთ",
    weekFri: "პარ",
    weekSat: "შაბ",
    weekSun: "კვი",
    reserving: "რეზერვირება...",
    slotsReservedFor: "სლოტები დარეზერვებულია თქვენთვის",
    completeBeforeExpiry: "დაასრულეთ ჯავშანი დროის ამოწურვამდე",
    reservationExpiredTitle: "რეზერვაციის ვადა ამოიწურა",
    reservationExpiredDesc: "თქვენი დროებითი რეზერვაციის ვადა ამოიწურა და სლოტები ხელმისაწვდომია სხვა მომხმარებლებისთვის. გთხოვთ აირჩიოთ ახალი სლოტები.",
    selectNewSlots: "ახალი სლოტების არჩევა",
    slotsAlreadyTaken: "არჩეული სლოტები უკვე აღარ არის ხელმისაწვდომი. გთხოვთ აირჩიოთ სხვა დრო.",
    someSlotsFailed: "ზოგიერთი სლოტი ვერ დადასტურდა. შესაძლოა ვადა ამოიწურა.",
    addAnotherDay: "სხვა დღის დამატება",
    wantAnotherDay: "გსურთ სხვა დღის დამატება?",
    doneSelectingDays: "არა, გაგრძელება",
    paymentTitle: "გადახდა",
    paymentSubtitle: "შეავსეთ გადახდა ჯავშნის დასადასტურებლად",
    orderSummary: "შეკვეთის შეჯამება",
    paymentMethod: "გადახდის მეთოდი",
    cardNumber: "ბარათის ნომერი",
    cardHolder: "ბარათის მფლობელი",
    expiryDate: "ვადის გასვლის თარიღი",
    cvv: "CVV",
    cardNumberPlaceholder: "1234 5678 9012 3456",
    cardHolderPlaceholder: "სახელი ბარათზე",
    expiryPlaceholder: "თთ/წწ",
    cvvPlaceholder: "123",
    billingAddress: "გადახდის მისამართი",
    billingAddressPlaceholder: "შეიყვანეთ თქვენი გადახდის მისამართი",
    payNow: "გადახდა ₾",
    paying: "მუშავდება...",
    securePayment: "დაცულია BOG გადახდის სისტემით",
    bogRedirectNote: "თქვენ გადამისამართდებით BOG-ის უსაფრთხო გადახდის გვერდზე ტრანზაქციის დასასრულებლად.",
  },
  settings: {
    title: "პარამეტრები",
    subtitle: "მართეთ თქვენი ანგარიში და პრეფერენციები.",
    tabs: {
      profile: "პროფილი",
      instructorProfile: "ინსტრუქტორის პროფილი",
      account: "ანგარიში",
      notifications: "შეტყობინებები",
    },
    profile: {
      photoTitle: "პროფილის ფოტო",
      photoDesc: "მართეთ თქვენი ფოტო ანგარიშის პარამეტრებში.",
      updateInAccount: "განაახლეთ ანგარიშში",
      availability: "ხელმისაწვდომობა",
      availabilityDesc: "დააყენეთ თქვენი ხელმისაწვდომობა კალენდრის გამოყენებით.",
      openCalendar: "კალენდრის გახსნა",
      personalInfo: "პირადი ინფორმაცია",
      notInstructor: "თქვენ ჯერ არ ხართ ინსტრუქტორი",
      title: "სათაური",
      locatedAt: "მდებარეობა",
      googleMapsUrl: "Google Maps ბმული",
      languageSkills: "ენების ცოდნა",
      other: "სხვა",
      selected: "არჩეული",
      none: "არცერთი",
      automaticCityPrice: "ავტომატიკის ქალაქის ფასი",
      automaticYardPrice: "ავტომატიკის მოედნის ფასი",
      manualCityPrice: "მექანიკის ქალაქის ფასი",
      manualYardPrice: "მექანიკის მოედნის ფასი",
      firstName: "სახელი",
      lastName: "გვარი",
      contactEmail: "საკონტაქტო ელ-ფოსტა",
      phone: "ტელეფონი",
      city: "ქალაქი",
      dateOfBirth: "დაბადების თარიღი",
      description: "აღწერა",
      address: "მისამართი",
      emailSecurityNote: "ელ-ფოსტის, პაროლის ან უსაფრთხოების პარამეტრების შესაცვლელად გადადით ანგარიშის ჩანართში.",
      profileUpdated: "პროფილი წარმატებით განახლდა",
      discardChanges: "ცვლილებების გაუქმება",
      saveChanges: "ცვლილებების შენახვა",
      vehiclePhotos: "ავტომობილის ფოტოები",
      uploadPhotos: "ფოტოების ატვირთვა",
      limitReached: "ლიმიტი ამოიწურა",
      loadingPhotos: "ფოტოები იტვირთება...",
      noPhotos: "ავტომობილის ფოტოები ჯერ არ არის ატვირთული.",
      photosUpdated: "ავტომობილის ფოტოები წარმატებით განახლდა",
      photoRemoved: "ავტომობილის ფოტო წარმატებით წაიშალა",
    },
    account: {
      title: "ანგარიშის მართვა",
      desc: "მართეთ თქვენი ანგარიშის პარამეტრები, უსაფრთხოება და დაკავშირებული ანგარიშები.",
    },
    notifications: {
      title: "შეტყობინებები",
      lessonReminders: "გაკვეთილის შეხსენებები",
      lessonRemindersDesc: "მიიღეთ შეტყობინება 24 საათით ადრე გაკვეთილის დაწყებამდე",
      newMessages: "ახალი წერილები",
      newMessagesDesc: "მიიღეთ ელ-წერილი ახალი შეტყობინების დროს",
      marketingUpdates: "სიახლეები",
      marketingUpdatesDesc: "მიიღეთ სიახლეები ფუნქციებისა და აქციების შესახებ",
      newBookings: "ახალი ჯავშნები",
      newBookingsDesc: "მიიღეთ შეტყობინება მოსწავლის ჯავშნის დროს",
      cancellations: "გაუქმებები",
      cancellationsDesc: "მიიღეთ შეტყობინება გაკვეთილის გაუქმებისას",
    },
  },
};
